#!/usr/bin/env bash
here=$(pwd)

set -e

cd "$(dirname "${BASH_SOURCE[0]}")"

echo "Update submodules ..."
git submodule update --init --recursive

function command_exists {
  command -v "$1" >/dev/null 2>&1
}

if [ -n "${SHELL##*zsh*}" ]; then
  echo -e "To use ZSH as default shell please do:\n"
  echo "  chsh -s $(which zsh)"
  echo "  env zsh"
  echo "  source ~/.zshrc"
fi

echo ""

deps=(zsh thefuck xclip awk vint ag)
echo "Make sure to have the following commands availble: ${deps[*]}, vim or neovim."
for cmd in "${deps[@]}"; do
  if ! command_exists "$cmd"; then
    echo "  - command $cmd not found."
  fi
done
echo "Also check the list of linters used by Vim:"
echo "https://github.com/w0rp/ale"

if ! command_exists vim && ! command_exists nvim; then
  echo "Neither vim, nor neovim were found."
fi

echo ""

if command_exists nvim; then
  echo "Please install python-neovim and python2-neovim neovim-remote (or python3-neovim) modules."
  echo "See https://github.com/neovim/neovim/wiki/Installing-Neovim."
fi

echo ""

# Install everything that is not a hidden directory or starts with + using GNU Stow
find . -maxdepth 1 -type d -not -iregex "^\.\(/[.+].*\)?" | sed "s~./~~" | xargs -L1 stow

cd "$here"
