#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
echo "Update submodules ..."
git submodule update --init --recursive  #"${DOTBOT_DIR}"

function command_exists {
  command -v "$1" >/dev/null 2>&1
}

if [ -n "${SHELL##*zsh*}" ]; then
  echo "To use ZSH as default shell please do:\n"
  echo "chsh -s $(which zsh)"
  echo "env zsh"
  echo "source ~/.zshrc"
fi

deps=(zsh thefuck xclip awk vint)
echo "Make sure to have the following commands availble: ${deps[@]}, vim or neovim."
for cmd in $deps; do
  if ! command_exists $cmd; then
    echo "Command $cmd not found."
  fi
done

if ! command_exists vim && ! command_exists nvim; then
  echo "Neither vim, nor neovim were found."
fi

if command_exists nvim; then
  echo "Please install python-neovim and python2-neovim (or python3-neovim) modules."
  echo "See https://github.com/neovim/neovim/wiki/Installing-Neovim."
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
