#!/usr/bin/env zsh
# vim: set foldmethod=marker filetype=zsh :

boot-asdf() {
  local asdf_url=https://github.com/asdf-vm/asdf.git

  export ASDF_DIR="$HOME/.local/opt/asdf"
  export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
  export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"

  if [ ! -d $ASDF_DIR ]; then
    echo -e "\`asdf\` not found. Downloading ...\n"
    mkdir -p "$(dirname "$ASDF_DIR")"
    mkdir -p "$(dirname "$ASDF_DATA_DIR")"
    ( umask -S g=r,o=r;
      git clone $asdf_url $ASDF_DIR
    )
    ( cd $ASDF_DIR;
      umask -S g=r,o=r;
      git checkout "$(git describe --abbrev=0 --tags)";
      chmod -R go-w .
    )
    echo -e "DONE\n=========================================================\n"
  elif (( $(old "$ASDF_DIR") > 30 )); then
    ( cd $ASDF_DIR;
      echo "\`asdf\` is too old. Fetching newest changes ...";
      git fetch --tags;
      umask -S g=r,o=r;
      git checkout "$(git describe --abbrev=0 --tags)"
      chmod -R go-w .
      touch .  # Make sure to change ctime of the repo, so it waits 30 days
    )
  fi
}

boot-asdf
unfunction asdf
source $ASDF_DIR/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)
autoload -Uz compinit
compinit
asdf "$@"
