#!/usr/bin/env zsh
# vim: set foldmethod=marker filetype=zsh :

if command-exists vimb && command-exists tabbed; then
  tabbed -c vimb -e "$@"
elif command-exists qutebrowser; then
  qutebrowser "$@"
elif command-exists cmd.exe; then
  cmd.exe /c start "microsoft-edge:$1"
else
  echo "Undefined browser"
fi
