#!/usr/bin/env zsh
# vim: set foldmethod=marker filetype=zsh :

# which ignores previous aliases but is not portable
# command does not ignore aliases, but is built in
# so it's better to try to check first with which and fallback to command
which "$1" &>/dev/null || command -v "$1" &>/dev/null
