#!/usr/bin/env zsh
# vim: set foldmethod=marker filetype=zsh :
# Consider https://www.funtoo.org/Keychain in the future

local SSH_ENV="$HOME/.ssh/environment"

ssh-agent-running() {
  (pgrep ssh-agent &>/dev/null) && (( ${+SSH_AUTH_SOCK} )) && [[ -e $SSH_AUTH_SOCK ]]
}

# Really check if it is running:
# __any_agent_running() {
#   ssh-add -l &>/dev/null
#   if [[ "$?" == 2 ]]; then  # No Agent running
#     return 1
#   fi
#   return 0
# }

if ! ssh-agent-running; then
  if [[ -r "$SSH_ENV" ]]; then
    eval "$(< "$SSH_ENV")" >/dev/null
  fi

  if ! ssh-agent-running; then  # Still cannot connect to agent
    rm -rf "$SSH_ENV"
    (umask 066; ssh-agent -s -t 3600 > "$SSH_ENV")
    eval "$(< "$SSH_ENV")" >/dev/null
  fi
fi
echo -e "* $(tput setaf 6)ssh-agent$(tput sgr0) is running\n"
