#!/usr/bin/env zsh
# vim: set foldmethod=marker filetype=zsh :

boot-asdf() {
  local asdf_version="v0.6.2"
  local asdf_url=https://github.com/asdf-vm/asdf.git
  local latest

  export ASDF_DIR="$HOME/.local/opt/asdf"
  export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
  export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"

  if [ ! -d $ASDF_DIR ]; then
    echo -e "\`asdf\` not found. Downloading ...\n"
    mkdir -p "$(dirname "$ASDF_DIR")"
    mkdir -p "$(dirname "$ASDF_DATA_DIR")"
    git clone --single-branch --branch $asdf_version $asdf_url $ASDF_DIR
    echo -e "DONE\n=========================================================\n"
  elif (( $(age $ASDF_DIR) > 30 )); then
    ( cd $ASDF_DIR;
      echo "\`asdf\` is too old. Fetching newest changes ...";
      git fetch --tags;
      latest="$(git describe --tags "$(git rev-list --tags --max-count=1)")";
      git checkout "$latest" &>/dev/null;
      touch .  # Make sure to change ctime of the repo, so it waits 30 days
    )
  fi
}

boot-asdf
unfunction asdf
source $ASDF_DIR/asdf.sh
source $ASDF_DIR/completions/asdf.bash
asdf "$@"
